### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [centricity11/prj-rev-bwfs-dasmoto#8]
Satisfactory 👍 

You've successfully reproduced the website according to the design mock. You've demonstrated a solid understanding of using HTML to markup your page's content and structure and of using CSS to apply fundamental styles.

Try to make more strategic use of `div` tags to divide and organize your content and of class names and IDs so that your code is as self-documenting as possible.

**Comment by centricity11** [comment]
Thank you for your comments. I appreciate that you took the time to explain your feedback, and I think it all makes sense.
